### ISSUE TITLE
Tests not passing on Python 3.7

### ISSUE THREAD

**Issue by omangin** [pubs/pubs#148]
See https://travis-ci.org/pubs/pubs/builds/390355455.

[edit] The issue actually comes with Python 3.7. It seems to be related to `pyfakefs`.

```
..../lib/python3.7/site-packages/beautifulsoup4-4.6.0-py3.7.egg/bs4/element.py:1615:` DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated, and in 3.8 it will stop working
  if (isinstance(value, str) or isinstance(value, collections.Callable) or hasattr(value, 'match')
..................................................................................................................................E.......................................
======================================================================
ERROR: test_list_several_no_date (test_usecase.TestList)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/omangin/code/pubs/tests/test_usecase.py", line 359, in test_list_several_no_date
    shutil.rmtree(os.path.join(self.rootpath, 'testrepo'))
  File ".../lib/python3.7/shutil.py", line 485, in rmtree
    _rmtree_safe_fd(fd, path, onerror)
  File "...env/lib/python3.7/shutil.py", line 400, in _rmtree_safe_fd
    with os.scandir(topfd) as scandir_it:
  File ".../lib/python3.7/site-packages/pyfakefs/fake_filesystem.py", line 3577, in scandir
    return self.filesystem.ScanDir(path)
  File ".../lib/python3.7/site-packages/pyfakefs/fake_filesystem.py", line 2857, in ScanDir
    return self.ScanDirIter(self, path)
  File ".../lib/python3.7/site-packages/pyfakefs/fake_filesystem.py", line 2813, in __init__
    self.path = self.filesystem.ResolvePath(path)
  File ".../lib/python3.7/site-packages/pyfakefs/fake_filesystem.py", line 1738, in ResolvePath
    file_path = os.fspath(file_path)
TypeError: expected str, bytes or os.PathLike object, not int
```

**Comment by omangin** [comment]
Submitted an issue upstream on Pyfakefs: https://github.com/jmcgeheeiv/pyfakefs/issues/421.

**Comment by omangin** [comment]
OK. So, the issue is already solved in Pyfakefs so we have two options here:
1. make the code compatible to Pyfakefs 3.4 to benefit from upstream updates,
2. backport the corresponding fix [pyfakefs/b3a4a78](https://github.com/jmcgeheeiv/pyfakefs/commit/b3a4a78e1363ac5b6922352a5ef715fb1e051edd) in the version we use.

@benureau Why were we stuck with the outdated Pyfakefs? On the long run it will probably be much better if we could depend on the latest recent version…

**Comment by benureau** [comment]
Yes, at the time the tests did not work with newer versions of pyfakefs, and there was no reason to upgrade. Now there is. I'll look into it.

**Comment by benureau** [comment]
I will look at it tomorrow.
