### ISSUE TITLE
remove does not work

### ISSUE THREAD

**Issue by humm** [pubs/pubs#24]
```
ttys009:~$ pubs remove Cheney2014
Are you sure you want to delete paper(s) [Cheney2014] (this will also delete associated documents)? [y]yes, [N]no

Traceback (most recent call last):
  File "/Users/fabien/.pyenv/versions/2.7.6/bin/pubs", line 5, in <module>
    pkg_resources.run_script('pubs==0.5.0', 'pubs')
  File "build/bdist.macosx-10.4-x86_64/egg/pkg_resources.py", line 488, in run_script
  File "build/bdist.macosx-10.4-x86_64/egg/pkg_resources.py", line 1361, in run_script
  File "/Users/fabien/.pyenv/versions/2.7.6/lib/python2.7/site-packages/pubs-0.5.0-py2.7.egg/EGG-INFO/scripts/pubs", line 5, in <module>
    pkg_resources.run_script('pubs==0.5.0', 'pubs')
  File "build/bdist.macosx-10.4-x86_64/egg/pubs/pubs_cmd.py", line 90, in execute
  File "build/bdist.macosx-10.4-x86_64/egg/pubs/commands/remove_cmd.py", line 26, in command
  File "build/bdist.macosx-10.4-x86_64/egg/pubs/uis.py", line 101, in input_yn
  File "build/bdist.macosx-10.4-x86_64/egg/pubs/uis.py", line 87, in input_choice
  File "build/bdist.macosx-10.4-x86_64/egg/pubs/uis.py", line 60, in input
  File "<string>", line 0

    ^
SyntaxError: unexpected EOF while parsing
```

If trying to answer the question: 
```
ttys009:~$ pubs remove Cheney2014
Are you sure you want to delete paper(s) [Cheney2014] (this will also delete associated documents)? [y]yes, [N]no
y
Traceback (most recent call last):
  File "/Users/fabien/.pyenv/versions/2.7.6/bin/pubs", line 5, in <module>
    pkg_resources.run_script('pubs==0.5.0', 'pubs')
  File "build/bdist.macosx-10.4-x86_64/egg/pkg_resources.py", line 488, in run_script
  File "build/bdist.macosx-10.4-x86_64/egg/pkg_resources.py", line 1361, in run_script
  File "/Users/fabien/.pyenv/versions/2.7.6/lib/python2.7/site-packages/pubs-0.5.0-py2.7.egg/EGG-INFO/scripts/pubs", line 5, in <module>
    pkg_resources.run_script('pubs==0.5.0', 'pubs')
  File "build/bdist.macosx-10.4-x86_64/egg/pubs/pubs_cmd.py", line 90, in execute
  File "build/bdist.macosx-10.4-x86_64/egg/pubs/commands/remove_cmd.py", line 26, in command
  File "build/bdist.macosx-10.4-x86_64/egg/pubs/uis.py", line 101, in input_yn
  File "build/bdist.macosx-10.4-x86_64/egg/pubs/uis.py", line 87, in input_choice
  File "build/bdist.macosx-10.4-x86_64/egg/pubs/uis.py", line 60, in input
  File "<string>", line 1, in <module>
NameError: name 'y' is not defined
```

Low hanging fruit probably, but I am not getting distracted right now.

**Comment by humm** [comment]
Ok, the ui issue has resolved with commit  0c51c5f36bd84075a1edad835bba34818ec7abee, but remove fails silently now. To be continued.
