### ISSUE TITLE
Bug in list when bib entry has no title

### ISSUE THREAD

**Issue by benureau** [pubs/pubs#30]
If a bibentry has no title, `pub list` breaks like so:

``` bash
$ pubs list
Traceback (most recent call last):
  File "/Users/fabien/.pyenv/versions/2.7.6/bin/pubs", line 5, in <module>
    pkg_resources.run_script('pubs==0.5.0', 'pubs')
  File "build/bdist.macosx-10.4-x86_64/egg/pkg_resources.py", line 488, in run_script
  File "build/bdist.macosx-10.4-x86_64/egg/pkg_resources.py", line 1354, in run_script
  File "/Users/fabien/.pyenv/versions/2.7.6/lib/python2.7/site-packages/pubs-0.5.0-py2.7.egg/EGG-INFO/scripts/pubs", line 5, in <module>
    pubs_cmd.execute()
  File "/Users/fabien/.pyenv/versions/2.7.6/lib/python2.7/site-packages/pubs-0.5.0-py2.7.egg/pubs/pubs_cmd.py", line 90, in execute
    cmd_funcs[cmd](args)
  File "/Users/fabien/.pyenv/versions/2.7.6/lib/python2.7/site-packages/pubs-0.5.0-py2.7.egg/pubs/commands/list_cmd.py", line 48, in command
    for p in papers))
  File "/Users/fabien/.pyenv/versions/2.7.6/lib/python2.7/site-packages/pubs-0.5.0-py2.7.egg/pubs/commands/list_cmd.py", line 48, in <genexpr>
    for p in papers))
  File "/Users/fabien/.pyenv/versions/2.7.6/lib/python2.7/site-packages/pubs-0.5.0-py2.7.egg/pubs/pretty.py", line 55, in paper_oneliner
    bibdesc = bib_oneliner(p.bibentry)
  File "/Users/fabien/.pyenv/versions/2.7.6/lib/python2.7/site-packages/pubs-0.5.0-py2.7.egg/pubs/pretty.py", line 36, in bib_oneliner
    title=bibentry['title'],
KeyError: 'title'
```

There are three lessons from that:
1. This should not happen, `list` should be robust to problems that affect isolated bibentries.
2. The formatting system needs to be waaaay more robust
3. title and author should probably be mandatory somehow, or at least generate a warning when they are not present during `add/edit/import` cmds.

**Comment by omangin** [comment]
It seems that this issue has been solved in version `0.6.0`. 

Regarding warnings on missing required fields, that's a good idea but that's a minor improvement that is not necessary for releasing `0.7.0`. Should we open a new issue for it?
