### ISSUE TITLE
No error on `pubs add file` if `file` is not a bibtex file

### ISSUE THREAD

**Issue by 73** [pubs/pubs#51]
Title says it all.

**Comment by humm** [comment]
Hi @73, Could you produce a reproducible example ? I does not work for me:

```
$ touch file
$ pubs add file
error: invalid bibfile file.
Traceback (most recent call last):
  File "/Users/fabien/.pyenv/versions/3.4.4/bin/pubs", line 4, in <module>
    __import__('pkg_resources').run_script('pubs==0.6.0', 'pubs')
  File "/Users/fabien/.pyenv/versions/3.4.4/lib/python3.4/site-packages/pkg_resources/__init__.py", line 735, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/Users/fabien/.pyenv/versions/3.4.4/lib/python3.4/site-packages/pkg_resources/__init__.py", line 1652, in run_script
    exec(code, namespace, namespace)
  File "/Users/fabien/.pyenv/versions/3.4.4/lib/python3.4/site-packages/pubs-0.6.0-py3.4.egg/EGG-INFO/scripts/pubs", line 9, in <module>
    pubs_cmd.execute()
  File "/Users/fabien/.pyenv/versions/3.4.4/lib/python3.4/site-packages/pubs-0.6.0-py3.4.egg/pubs/pubs_cmd.py", line 87, in execute
    args.func(conf, args)
  File "/Users/fabien/.pyenv/versions/3.4.4/lib/python3.4/site-packages/pubs-0.6.0-py3.4.egg/pubs/commands/add_cmd.py", line 101, in command
    base_key = bibstruct.extract_citekey(bibentry)
  File "/Users/fabien/.pyenv/versions/3.4.4/lib/python3.4/site-packages/pubs-0.6.0-py3.4.egg/pubs/bibstruct.py", line 43, in extract_citekey
    citekey, entry = get_entry(bibdata)
  File "/Users/fabien/.pyenv/versions/3.4.4/lib/python3.4/site-packages/pubs-0.6.0-py3.4.egg/pubs/bibstruct.py", line 38, in get_entry
    verify_bibdata(bibdata)
  File "/Users/fabien/.pyenv/versions/3.4.4/lib/python3.4/site-packages/pubs-0.6.0-py3.4.egg/pubs/bibstruct.py", line 33, in verify_bibdata
    raise ValueError(u"no valid bibdata")
ValueError: no valid bibdata
```

**Comment by 73** [comment]
1. There should not be a trace.
2. Try to add http://ieeexplore.ieee.org/stamp/stamp.jsp?arnumber=6234405

**Comment by omangin** [comment]
Here is what I get:
- when downloading the file manually and then adding it:
```
$ pubs add 06234405.pdf
error: 'utf-8' codec can't decode byte 0x80 in position 10: invalid start byte
```

- when adding the web address:
```
$ pubs add 'http://ieeexplore.ieee.org/stamp/stamp.jsp?arnumber=6234405'
error: invalid bibfile http://ieeexplore.ieee.org/stamp/stamp.jsp?arnumber=6234405.
error: no valid bibdata
dowloading http://ieeexplore.ieee.org/stamp/stamp.jsp?arnumber=6234405
```

- when using `pubs add -d 'http://ieeexplore.ieee.org/stamp/stamp.jsp?arnumber=6234405'` it correctly opens an editor to fill in the bibtex file.

**Comment by 73** [comment]
My case was the first one, downloading and then adding (should have explained, mea culpa). 
```
error: 'utf-8' codec can't decode byte 0x80 in position 10: invalid start byte
```
It not the correct error, isn't it? It is not a hard bug, just something that should be fixed sometime.

**Comment by omangin** [comment]
Yes. Indeed. This should be catched by the `read_file` method from `content.py`. Actually this method should be called `read_text_file` and should catch and re-raise the error with a more explicit docstring like "Unknown encoding (maybe not a text file) for: ...". It is typically the kind of cases that @humm mentions in his comment to #52.
